### ISSUE TITLE
RSS OPML only pulls last article

### ISSUE THREAD

**Issue by issmirnov** [paulbricman/shannon-nutri-score#3]
## Summary

Adding RSS from OPML only pulls the last article.

## Details

After setting up lexiscore, I take my blog's RSS (https://ivans.io/rss/) and convert it to OPML using https://opml-gen.ovh/. This yields the following file:

```xml
<opml version="2.0">
	<body>
		<outline text="Subscriptions" title="Subscriptions">
			<outline xmlUrl='https://ivans.io/rss/' />
	
		</outline>
	</body>
</opml>
```

After adding this to lexiscore, only the most recent article appears in the reading list. I've checked the RSS feed, and all articles are fully present.

## Desired Behavior

RSS feeds should pull all articles.

**Comment by issmirnov** [comment]
I don't have time to debug this week, but perhaps it's worth trying my provided input with a debugger at https://github.com/paulbricman/lexiscore/blob/5ed0447e9d31762e2ed5b027c86f88fba90417a4/connectors.py#L19 to see what the OPML dump results in.

**Comment by paulbricman** [comment]
Thanks for creating a separate issue! Are you sure the "max days ago" field in the "add input source" section covers the desired articles?

**Comment by issmirnov** [comment]
Ah, good to know. I didn't realize that that was the backwards buffer range. I set it to 500 days, but it only pulled the last few articles. 

Lexiscore:
![image](https://user-images.githubusercontent.com/5771615/145488288-ddd776e5-d7cb-4662-8ba3-21e7dc875cbf.png)



Blog page:
![image](https://user-images.githubusercontent.com/5771615/145488310-9475db95-8e5c-48a6-a425-358640185132.png)

I notice that the list of articles isn't the most recent 6 published. Is there some sort of filtering mechanism that may omit articles?

**Comment by paulbricman** [comment]
@issmirnov, yeah some super short articles are ignored from the start. I think I did that so that some RSS entries only containing links to some podcast episode or something wouldn't show up. But if I think about it, this responsibility should be the author's, having different feeds in place for articles/announcements/etc. So I might just remove that filter.

Also, I'm not sure what causes the low skill estimates, but I'd guess the reason is a fresh conceptarium without that many entries? I'll create an enhancement issue for removing the filter, but let me know if you feel somethings wrong with the estimates in another issue.
